language: python
python:
  - "3.6"
before_install:
  - pip install pycodestyle codecov
  - python setup.py install
script:
  - pycodestyle --exclude=venv --ignore=E501 .
  - pytest
  - coverage run --branch --source=. -m unittest discover -bv
  - coverage report -m
after_success:
  - codecov
